### ISSUE TITLE
KeyError : csrftoken

### ISSUE THREAD

**Issue by mickelastrologer** [tnychn/instascrape#15]
![IMG_20201122_180858](https://user-images.githubusercontent.com/74862455/99904250-c642bb00-2cef-11eb-9d5d-8ad95348008c.jpg)

**Comment by tnychn** [comment]
Duplicate of #2.

**Comment by mickelastrologer** [comment]
@tnychn give me the solution

**Comment by NOBHACKER120** [comment]
I tried #2 but not working also
