### ISSUE TITLE
Post Filter Expressions

### ISSUE THREAD

**Issue by KeksTheAllmighty** [tnychn/instascrape#21]
Hey guys, first of all thank you for the great tool! Now I want to use it to scrape a user's recent posts (like posts from last 24 hours). Now while the option`recent` doesnt work for users i think that it should be possible to download the posts using the ` -PF <expression>, --posts-filter <expression>` option.

The problem is, i couldnt find the description about what it does. Can you maybe tell me the correct setting for this expression?

**Comment by tnychn** [comment]
It's a Python conditional expression. In your case, you can use `-PF "created_time >= 1615600800"`.

**Comment by KeksTheAllmighty** [comment]
Heey, thank you for your answer, already figured that out :) so for me the filter expression for last 24 hours posts looks like:
```
currentstamp=$(date +%s)
instascrape download -recent -PF "created_time >= $currentstamp - 86400" "@#name" -l 10 -d output.txt
```
