### ISSUE TITLE
Login with library

### ISSUE THREAD

**Issue by akasaa101** [tnychn/instascrape#25]
How can I login with library?
I tried to login with 

```
from instascrape import Instascraper

with Instascraper() as insta:
    insta.login("username","password")
    posts = insta.profile("target account").story()
    posts.download_all(dest="./output")
```

But its return as : 

instascrape.exceptions.CheckpointChallengeRequired: Failed to log into Instagram. (message: 'checkpoint challenge solving is required')

**Comment by tnychn** [comment]
Catch the `CheckpointChallengeRequired` exception and handle it by calling `insta.checkpoint_challenge_login`.
https://github.com/tnychn/instascrape/blob/e136bb9f6037aed273b37001ab64d933b720cf75/instascrape/instascrape.py#L157-L193
